name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.8.2  # o la que estiguis usant

      - name: Configure Poetry to not use virtualenvs
        run: poetry config virtualenvs.create false

      - name: Install dependencies
        run: poetry install

      - name: Show versions
        run: |
          python --version
          poetry --version
          poetry show

      - name: Run Ruff (lint)
        run: poetry run ruff .

      - name: Run Tests
        run: poetry run pytest
